### ISSUE TITLE
Ex file will not open on PC

### ISSUE THREAD

**Issue by tomgriner** [rrirower/json-feed-manager#1]
Hello Michael. I have uninstalled the Json Feed Manager 2019. I downloaded the Github version and tried to install it. I required an upgrade to NetFrame 4. As I have tried to install this, my system says NetFrame 4 already installed or higher.  So this is the jam up. When I try to launch the new Github Json Feed Manager the loading hiccups with the request for Net Framework 4 which I already have. Thanks, Tom Griner

Details

Microsoft .NET Framework 4 is already a part of this operating system.  You do not need to install the .NET Framework 4 redistributable. <A HREF="http://go.microsoft.com/fwlink/?LinkId=164207">More information</A>. 

Same or higher version of .NET Framework 4 Client Profile has already been installed on this computer.

**Comment by rrirower** [comment]
Tom...Please go to Windows 'Control Panel'/Uninstall a program and list all versions of the .NET Framework you have installed.
