### ISSUE TITLE
SSL certificate updated 

### ISSUE THREAD

**Issue by detaron1** [rrirower/json-feed-manager#28]
I have a quick question, roku updated their system and the vast tag I was using for advertising isn’t working due to SSL certificate update. I asked the advertising company could they fixed their vast tag but they said SSL certificate is something I’ll have to updated within my roku feed. I’m not sure how to do this, is this possible to add this SSL certificate in your software? They sent me this link below. 
https://calnetweb.berkeley.edu/calnet-technologists/incommon-sectigo-certificate-service/addtrust-external-root-expiration-may-2020

**Comment by rrirower** [comment]
Your feed file does not control the Vast tag.  That's managed within the Roku developer portal under the 'Monetization' tab.

**Comment by detaron1** [comment]
Yes I know but the vast tag was working until roku updated their system and now it’s saying SSL certificate expired. The advertising company is saying it’s from the roku feed not their vast tag.

**Comment by rrirower** [comment]
As I said, there is nothing in your feed file that controls the Vast tag.  Please have a look at the [Roku Json Schema ](https://developer.roku.com/docs/specs/direct-publisher-feed-specs/json-dp-spec.md) for more info.  You need to make that change in the Developer Portal.  If you need more help, you'll need to contact Roku Partner Success.
