### ISSUE TITLE
feed url 

### ISSUE THREAD

**Issue by Lucifer123-coder** [rrirower/json-feed-manager#31]
Sir,
Please help me to solve the issue,
I had created a json code through this software but please help me in the matter - "how to create feed url for roku tv through json file"; because Roku Tv is asking feed url

**Comment by rrirower** [comment]
I'll try to help, but, I need to know what your problem is.  Please describe your problem in detail.

**Comment by Lucifer123-coder** [comment]
Hi sir,
In continuation with previous mail, sir I am making a tv channel for Roku
tv so it asks for feed url at developer.roku.com and there they say you can
make a json live feed url, for example -
https://developer.roku.com/en-gb/docs/direct-publisher/tutorial/feed-url.md


I created feed format for live video as given in example on this link :-
https://developer.roku.com/en-gb/docs/specs/direct-publisher-feed-specs/json-dp-spec.md
.

So please help in making json feed url I had made json file :-

https://drive.google.com/file/d/1WNMf8SO6lElpwZFYiA-LIeRsAXhivfrj/view?usp=drivesdk

Hope you understand me what I am looking for.
Regards,
Gyanesh shivam

**Comment by rrirower** [comment]
Once you've created your feed file, you must upload it to a webserver that Roku can access.  I use Amazon S3 to store my feed file.  Then, as the tutorial says, you must tell Roku where to find your feed file in the Developer's portal.

**Comment by Lucifer123-coder** [comment]
Sir,
I have a server I don't know what's the name of the server it's in Chennai,
India.
So I stream 24x7 live programme for that purpose I have hls play url as I
mentioned in the json code file.
Ok let me tell do you know about instanttvchnnel.com, firstly that website
have helped me in creating json feed url everything work fine but I wasnot
able to monetize my Roku tv channel, so I created json code but don't know
how to get feed url of that, or like I have checked my json code on
  https://www.jsonschemavalidator.net/  it worked fine and returned no
error message so I am damn sure json code is error free but don't know what
to type in feed url,
Please sir help me in this matter to fix this.
Regards,
Gyanesh shivam.

**Comment by rrirower** [comment]
If you don't have access to your webserver, there's nothing I can do to help you.  As I said, you must upload your JSON feed file to a webserver that is accessible to Roku.  Once you've uploaded the JSON feed file to the server, you use the URL of that file in the Roku developer portal to tell Roku where to find your feed file.

**Comment by Lucifer123-coder** [comment]
Sir,
In continuation with previous mail,
I am not able to get (understand) what's the meaning of Json feed file is
it the file, is it this file (
https://drive.google.com/file/d/1WNMf8SO6lElpwZFYiA-LIeRsAXhivfrj/view?usp=drivesdk
), or the file which i am doing live streaming having url (
RTMP Play Url
rtmp://seventv.livebox.co.in:1935/sevenwonderstv/live

Preview Link
http://seventv.livebox.co.in/livebox/player/?chnl=sevenwonderstv

Hls Play URl
http://seventv.livebox.co.in/sevenwonderstvhls/live.m3u8


Dash Play Url
http://seventv.livebox.co.in/sevenwonderstvdash/live.mpd
)

**Comment by rrirower** [comment]
The feed file is the file that was created using the Json Feed Manager software.  It creates a ".json" file that must be uploaded to your webserver.

**Comment by Lucifer123-coder** [comment]
Hi sir,
In continuation with your mail, thank you sir for clearing my doubt but can
you give me an example of webserver I mean name which will be of very
cheaper rate because I have to upload a file which is in size of 3-4kb so
to get the url of that json feed file

**Comment by rrirower** [comment]
I can't tell you what webserver to use.  I use Amazon S3, but, you should ask your question on the Roku forum.

**Comment by Lucifer123-coder** [comment]
Closed #31
