### ISSUE TITLE
Update: Roku Error Message

### ISSUE THREAD

**Issue by JLNjolo** [rrirower/json-feed-manager#32]
I installed Windows 10 on a spare pc, then installed your latest RJFM software (version 2.0.2.7) and created one .bif file in the software corresponding to one video. I then uploaded the .bif file to hostgator and saved the json file then tested it on Roku.  My purpose was to discover (if possible) the issue "1 item has an error: Required trickPlayFile url is unreachable". The bif file created was 935mb, which is larger than the 24 minute video. This seems accessive.
![error](https://user-images.githubusercontent.com/55280239/89882212-80c10e80-db94-11ea-9358-df4bff717c59.jpg)

Since the error still appears, my conclusion is that since the video file is stored on a Vimeo Pro account, Roku will not accept it because it is not streamed from a CDN.  I don't know. The video link is a single FHD video, not segmented and playable on multiple devices.

Another thing I discovered is that your RJFM software (version 2.0.2.7) deletes the bitrate code in all videos when saving a json file. When testing on Roku that didn't cause an error message. Perhaps Roku doesn't require bitrate now?

**Comment by rrirower** [comment]
I've created several .bif files that work correctly.  But, I'm streaming them from Amazon S3 with CloudFront.  Additionally, when I created them, I specified the quality as HD and not FHD.  That would explain the large size of the file versus my file(s) that is typically in the megabytes.

**Comment by rrirower** [comment]
As for the message you receive, you should probably contact Roku Partner Sucess to see why they can't seem to locate your .bif file.  And, yes, bitrate is no longer needed.
