### ISSUE TITLE
Can't get Series items to play 

### ISSUE THREAD

**Issue by Green-Hornet** [rrirower/json-feed-manager#42]
Cant get series items to play.
Is there a demo template on ho to play each category type? can the Category files play from a playlist the same as a short form video?

I do not see how it knows which file to play from the series id, the sub series id's are not shown anywher.

Is there a sample chanel that show each video type and what is needed to play?

**Comment by rrirower** [comment]
"Can't get series items to play." - Does that mean that they don't show on your Roku?  Can you be more specific?

"Categories" (and playlists) are simply a way to sort your videos within your channel.

A "Series" object contains either a set of "Episodes" (which are identified by an id), or, a set of "Seasons" that contain "Episodes".   The Series id is not used to play the actual episode.  It simply provides a unique identifier for each parent object within your feed file.

**Comment by Green-Hornet** [comment]
Thanks

It looks like the issue was that I “copied” the series and did not change the episode from 1 to 2, etc.

 

*Maybe a good request would be that when you save the feed, it checks that there are no duplicate episodes within a series, for when someone may have copied an item.

 

 

Also I had the hardest time with understanding the Category and playlist and the software allowed me to have both.

*Maybe a suggestion request would be to check if category has a playlist, or visa versa, and an option to pick one or the other, which would remove the offending item.

     e.g.  if I wanted to use playlists, it would check the category to see if playlist was in there and remove it.

 

Gavin Giles

804-873-3276

**Comment by Green-Hornet** [comment]
Thanks

It looks like the issue was that I “copied” the series and did not change the episode from 1 to 2, etc.

 

*Maybe a good request would be that when you save the feed, it checks that there are no duplicate episodes within a series, for when someone may have copied an item.

 

 

Also I had the hardest time with understanding the Category and playlist and the software allowed me to have both.

*Maybe a suggestion request would be to check if category has a playlist, or visa versa, and an option to pick one or the other, which would remove the offending item.

     e.g.  if I wanted to use playlists, it would check the category to see if playlist was in there and remove it.

 

Gavin Giles

804-873-3276

**Comment by rrirower** [comment]
Thanks for the info.  When a Series is copied the software should assign new ids to the Episode objects.  That's a bug and will be fixed in a future release.

As for Categories and Playlists, they are distinct.  A category is either defined by a Query or a Playlist.

Please close this issue if it is resolved.
