### ISSUE TITLE
Json feed manager for direct publisher

### ISSUE THREAD

**Issue by johnsonelahi** [rrirower/json-feed-manager#45]
Hello there, 
When I installed the new version of JSON feed manager then I open the software the JSON feed manager did not open. please fix this issue. Thank you

**Comment by rrirower** [comment]
I'll need a little bit more info than what you've provided.  Is this a clean install?  What version of Windows and .Net are installed?  Did you check all of the installation requirements before installing?

Any other information that helps define what the problem is you're seeing would help, including any messages you receive.

**Comment by johnsonelahi** [comment]
Windows 10 .Net framework 4.8

**Comment by rrirower** [comment]
Since I have no other users reporting this issue, I'll need to know more info.  Please describe how you are attempting to install the software and what you are seeing on the screen.  Any messages?  Have you tried a reboot?  Is this a clean install?

Any and all info is helpful.
Thanks.

**Comment by johnsonelahi** [comment]
When I uninstall and reinstall the software, it pops up at the bottom of the taskbar. But there is no show on the screen. There is an icon shown in the taskbar.

**Comment by johnsonelahi** [comment]
Do you have WhatsApp, then will send you the video

**Comment by johnsonelahi** [comment]
Can I use JSON feed manager on windows 7?

**Comment by johnsonelahi** [comment]
Here is the link to video
https://we.tl/t-XCJjnlaTSA

**Comment by johnsonelahi** [comment]
Hello there,
Sir, Is it possible, Can I make sub-categories in the Json feed manager?

**Comment by rrirower** [comment]
I'm not sure what you mean by 'sub-categories'?  However, it sounds like you want to define Series with Episodes.  Is that correct?

Keep in mind, the software is governed by the [Roku Direct Publisher Feed Schema](https://developer.roku.com/docs/specs/direct-publisher-feed-specs/json-dp-spec.md#content).

**Comment by rrirower** [comment]
Closing this since there is no response from the user.
