### ISSUE TITLE
Live fast channel does not display content, only categories

### ISSUE THREAD

**Issue by coskel22** [rrirower/json-feed-manager#48]
### Discussed in https://github.com/rrirower/json-feed-manager/discussions/47

<div type='discussions-op-text'>

<sup>Originally posted by **coskel22** February 24, 2022</sup>
Used JFM to build out a "live" fast channel, a single feed of 24 hour content. Using Roku Direct Publisher
Because it would not validate without categories, I added categories. Now I just have a list of categories, all of which say "live" and when I press any of them, no content plays, and it reverts back to the main screen with the category list.

I would prefer for the channel to just load and run, and have content tags instead of categories, or just one category if I have to.

How can I accomplish this?
Current setup:
![image](https://user-images.githubusercontent.com/100377158/155587333-e9d95e34-4f97-4b6f-84c7-d09814df472c.png)

Thanks in advance</div>

**Comment by rrirower** [comment]
Closed.  No action.
