### ISSUE TITLE
Adding episodes and seasons

### ISSUE THREAD

**Issue by Stream82** [rrirower/json-feed-manager#49]
I am trying to add episodes to a series but when I right click on series parent item, the software crashes.  Not sure how to add episodes and seasons to a series.

**Comment by Stream82** [comment]
I am using 2.0.3.2.  I add a series item and enter info for it. I am trying to add episode but am unsure exactly how to do this.  I right click on the new series to add and item but a crash report window shows up.

**Comment by rrirower** [comment]
I can confirm it is a bug.  I'll be looking at this and let you know when I have a fix.

**Comment by rrirower** [comment]
I've isolated the bug and believe I have a fix.  I'll need to test it a bit before releasing it.  It should be available early next week.

**Comment by rrirower** [comment]
Fixed in 2.0.3.3
