### ISSUE TITLE
BIF Generation doesn't create files

### ISSUE THREAD

**Issue by pattonjh** [rrirower/json-feed-manager#50]
I am a new user and it's possible I'm doing something wrong.

I have a feed created and have all of the information filled out. I click the Generate button for BIF files, and the app says that it's generating them. After a couple of seconds I get a taskbar notification that generation is complete. However, there are no files in the folder that it's supposed to save them to. I tested both with the destination folder empty (that is, it's using the default) and with a custom folder.

In all cases, there are no BIF files generated despite the app and log thinking that it is complete.

Here is the created JSON file (saved as a txt file because github complained about the .json format)
[random-logic.txt](https://github.com/rrirower/json-feed-manager/files/9294253/random-logic.txt)

Here's the snippet from the log file:
2022-08-09 15:09:34.1813 INFO Generating BIF files for '<FILE URL>'.
2022-08-09 15:09:34.1813 INFO Building Task payload for TPFMaker.
2022-08-09 15:09:34.1813 INFO Spawning 'TPFMaker' for BIF generation of 1 video(s).
2022-08-09 15:09:35.0285 INFO BIF generation complete.

Thanks!

**Comment by rrirower** [comment]
Sorry for any confusion.  However, the BIF generation is handled internally by a Roku supplied tool that does not work with playlists (ie. **.m3u8** file types).  I tried creating the BIF with the stand alone [Trick Play File Maker](https://github.com/rrirower/trick-play-file-maker) tool and the same error occurs.

You've defined the content as a Short form video.  These types of content aren't typically defined as a playlist.

**Comment by pattonjh** [comment]
For what it's worth, this is not a playlist as defined by Roku's content feed. It is an HLS video.

I understand that the m3u8 file defines something that is akin to a playlist of short video chunks. I just wanted to be clear that it's not a playlist in the sense that Roku allows you to define a playlist.

Thanks.
